apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sentry-node
  description: simple node wrapper around the Sentry API
  owner: unknown
spec:
  type: unknown
  lifecycle: production
  owner: unknown
  system: Clever
